#!/usr/bin/env python3
"""Validate canonical V1 vectors and generate a dependency-free C header."""

from __future__ import annotations

import argparse
import json
import re
import struct
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent
SOURCE = ROOT / 'v1_vectors.json'
DEFAULT_OUTPUT = ROOT / 'generated' / 'v1_vectors.h'
HEADER = struct.Struct('<BBBBBBHH')


def _identifier(name: str) -> str:
    return re.sub(r'[^A-Za-z0-9]+', '_', name).strip('_').upper()


def _bytes_literal(data: bytes) -> str:
    lines = []

    for start in range(0, len(data), 12):
        chunk = data[start:start + 12]
        lines.append(
            '    ' + ', '.join(f'0x{value:02X}U' for value in chunk)
        )

    return ',\n'.join(lines)


def _validate_and_load() -> dict:
    document = json.loads(SOURCE.read_text(encoding='utf-8'))

    if document['schemaVersion'] != 1:
        raise ValueError('unsupported vector schemaVersion')

    if document['headerSize'] != HEADER.size:
        raise ValueError('headerSize does not match the V1 header')

    max_payload = document['maxPayloadSize']
    known_flags = document['knownFlagsMask']
    names = set()

    if known_flags != sum(document['flags'].values()):
        raise ValueError('knownFlagsMask does not match registered flags')

    for vector in document['validMessages']:
        name = vector['name']

        if name in names:
            raise ValueError(f'duplicate vector name: {name}')

        names.add(name)
        payload = bytes.fromhex(vector['payloadHex'])
        expected = bytes.fromhex(vector['messageHex'])

        if len(payload) > max_payload:
            raise ValueError(f'{name}: payload exceeds maxPayloadSize')

        if vector['flags'] & ~known_flags:
            raise ValueError(f'{name}: contains unknown flags')

        encoded = HEADER.pack(
            vector['version'],
            vector['flags'],
            vector['src'],
            vector['dst'],
            vector['service'],
            vector['opcode'],
            vector['seq'],
            len(payload),
        ) + payload

        if encoded != expected:
            raise ValueError(f'{name}: fields do not match messageHex')

    for vector in document['invalidMessages']:
        name = vector['name']

        if name in names:
            raise ValueError(f'duplicate vector name: {name}')

        names.add(name)
        bytes.fromhex(vector['messageHex'])

    return document


def _render(document: dict) -> str:
    output = [
        '/* Generated by generate_v1_vectors.py. Do not edit manually. */',
        '#ifndef V1_GOLDEN_VECTORS_H',
        '#define V1_GOLDEN_VECTORS_H',
        '',
        '#include <stddef.h>',
        '#include <stdint.h>',
        '',
        f'#define V1_GOLDEN_PROTOCOL_VERSION '
        f'{document["protocolVersion"]}U',
        f'#define V1_GOLDEN_HEADER_SIZE {document["headerSize"]}U',
        f'#define V1_GOLDEN_MAX_PAYLOAD_SIZE '
        f'{document["maxPayloadSize"]}U',
        f'#define V1_GOLDEN_KNOWN_FLAGS_MASK '
        f'{document["knownFlagsMask"]}U',
        '',
    ]

    for group_name, prefix in (
        ('flags', 'FLAG'),
        ('nodes', 'NODE'),
        ('services', 'SERVICE'),
        ('systemOpcodes', 'SYSTEM'),
        ('motionOpcodes', 'MOTION'),
    ):
        for name, value in document[group_name].items():
            output.append(
                f'#define V1_GOLDEN_{prefix}_{_identifier(name)} '
                f'{value}U'
            )

        output.append('')

    output.extend([
        'typedef struct',
        '{',
        '    const char *name;',
        '    const uint8_t *message;',
        '    size_t message_length;',
        '    uint8_t version;',
        '    uint8_t flags;',
        '    uint8_t src;',
        '    uint8_t dst;',
        '    uint8_t service;',
        '    uint8_t opcode;',
        '    uint16_t seq;',
        '    uint16_t payload_length;',
        '} V1GoldenValidVector;',
        '',
        'typedef struct',
        '{',
        '    const char *name;',
        '    const uint8_t *message;',
        '    size_t message_length;',
        '    const char *expected_error;',
        '} V1GoldenInvalidVector;',
        '',
    ])

    for vector in document['validMessages']:
        identifier = _identifier(vector['name'])
        data = bytes.fromhex(vector['messageHex'])
        output.extend([
            f'static const uint8_t V1_{identifier}_MESSAGE[] =',
            '{',
            _bytes_literal(data),
            '};',
            '',
        ])

    for vector in document['invalidMessages']:
        identifier = _identifier(vector['name'])
        data = bytes.fromhex(vector['messageHex'])
        output.extend([
            f'static const uint8_t V1_{identifier}_MESSAGE[] =',
            '{',
            _bytes_literal(data),
            '};',
            '',
        ])

    output.extend([
        'static const V1GoldenValidVector V1_GOLDEN_VALID_VECTORS[] =',
        '{',
    ])

    for vector in document['validMessages']:
        identifier = _identifier(vector['name'])
        payload_length = len(bytes.fromhex(vector['payloadHex']))
        output.extend([
            '    {',
            f'        "{vector["name"]}",',
            f'        V1_{identifier}_MESSAGE,',
            f'        sizeof(V1_{identifier}_MESSAGE),',
            f'        {vector["version"]}U,',
            f'        {vector["flags"]}U,',
            f'        {vector["src"]}U,',
            f'        {vector["dst"]}U,',
            f'        {vector["service"]}U,',
            f'        {vector["opcode"]}U,',
            f'        {vector["seq"]}U,',
            f'        {payload_length}U',
            '    },',
        ])

    output.extend([
        '};',
        '',
        'static const size_t V1_GOLDEN_VALID_VECTOR_COUNT =',
        '    sizeof(V1_GOLDEN_VALID_VECTORS) /',
        '    sizeof(V1_GOLDEN_VALID_VECTORS[0]);',
        '',
        'static const V1GoldenInvalidVector V1_GOLDEN_INVALID_VECTORS[] =',
        '{',
    ])

    for vector in document['invalidMessages']:
        identifier = _identifier(vector['name'])
        output.extend([
            '    {',
            f'        "{vector["name"]}",',
            f'        V1_{identifier}_MESSAGE,',
            f'        sizeof(V1_{identifier}_MESSAGE),',
            f'        "{vector["expectedError"]}"',
            '    },',
        ])

    crc_vector = document['crcVectors'][0]
    crc_data = bytes.fromhex(crc_vector['dataHex'])
    output.extend([
        '};',
        '',
        'static const size_t V1_GOLDEN_INVALID_VECTOR_COUNT =',
        '    sizeof(V1_GOLDEN_INVALID_VECTORS) /',
        '    sizeof(V1_GOLDEN_INVALID_VECTORS[0]);',
        '',
        'static const uint8_t V1_GOLDEN_CRC_DATA[] =',
        '{',
        _bytes_literal(crc_data),
        '};',
        '',
        'static const uint16_t V1_GOLDEN_CRC_EXPECTED =',
        f'    0x{crc_vector["expected"]:04X}U;',
        '',
        '#endif',
        '',
    ])

    return '\n'.join(output)


def main() -> int:
    """Generate the header or verify that the tracked copy is current."""
    parser = argparse.ArgumentParser()
    parser.add_argument('--check', action='store_true')
    parser.add_argument('--output', type=Path, default=DEFAULT_OUTPUT)
    arguments = parser.parse_args()
    document = _validate_and_load()
    rendered = _render(document)

    if arguments.check:
        if not arguments.output.exists():
            print(
                f'missing generated header: {arguments.output}',
                file=sys.stderr,
            )
            return 1

        if (
            arguments.output.read_text(encoding='utf-8')
            != rendered
        ):
            print(
                f'generated header is stale: {arguments.output}',
                file=sys.stderr,
            )
            return 1

        return 0

    arguments.output.parent.mkdir(parents=True, exist_ok=True)
    arguments.output.write_text(
        rendered,
        encoding='utf-8',
    )
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
