[platformio]
build_dir = ../../build/platformio/esp32cam_gimbal
src_dir = .

[env:esp32cam]
platform = espressif32
board = esp32cam
framework = arduino
monitor_speed = 115200
build_flags =
    -Wall
    -Wextra
    -Werror=return-type
